name: "vm" # 项目名字
dataDir: "D:/configuration" # 数据库所在位置
rootDir: "D:/workspaces/vm"  # 项目空间目录
workDir: "D:/workspaces/vm"  # 工作空间目录
env: "development"  # 项目当前环境
services:
  basic: # 服务配置
    host: "localhost"
    port: "36001"
    database: "basic"
    dataPort: "3680"
  service: # 服务配置
    host: "localhost"
    port: "36002"
    database: "basic"
    dataPort: "3680"
  auth: # 服务配置
    host: "localhost"
    port: "36003"
    database: "basic"
    dataPort: "3680"
  user: # 服务配置
    host: "localhost"
    port: "36004"
    database: "basic"
    dataPort: "3680"
  rule: # 服务配置
    host: "localhost"
    port: "36005"
    database: "basic"
    dataPort: "3680"